# Generated by Django 2.1.5 on 2019-01-16 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, null=True, unique=True)),
                ('content', models.TextField()),
                ('keyword', models.CharField(max_length=8, null=True)),
                ('description', models.CharField(max_length=25, null=True)),
                ('icon', models.ImageField(null=True, upload_to='upload')),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='user.Category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('crate_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='f',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='user.Category'),
        ),
    ]
